version: '3.9'

services:
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./entrypoint/mongo/init_db.js:/docker-entrypoint-initdb.d/init_db.js
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 5
  postgres:
    image: postgres:13
    restart: always
    volumes:
      - postgresql:/var/lib/postgresql/data
      - ./entrypoint/pg:/docker-entrypoint-initdb.d
    env_file:
      - .env
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_DBNAME}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U app -d movies_database" ]
      interval: 10s
      timeout: 5s
      retries: 5
  test:
    build: .
    env_file:
      - .env
    volumes:
      - ./results:/storage_research/results
    depends_on:
      postgres:
        condition: service_healthy
      mongo:
        condition: service_healthy
volumes:
  postgresql:
    name: pg_volume_test
